# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
