# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmanager', '0002_auto_20151227_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
